### ISSUE TITLE
ReactQuill Inline Formatting Not Working

### ISSUE THREAD

**Issue by DiegoPerez1441** [DiegoPerez1441/No-Pad#2]
## Problem
When using ReactQuill to edit notes in the `Note.js` component, inline formatting such as **Bold**, _Italic_, Underline don't display properly. The note content is being received and sent to Firebase Firestore correctly and after some further testing this seems to be an issue with ReactQuill not rendering certain formats correctly.

### react-quill v1.3.5
package.json: `"react-quill": ^1.3.5`
package-lock.json: `"react-quill": ^1.3.5`

**Comment by DiegoPerez1441** [comment]
## Possible Causes
- quilljs/react-quill not accepting bold and italic formats
- Display bug with Chrome
- CSS overriding or importing quill/react-quill theme incorrectly
- Wrong setup of quill/react-quill

## Update
- I tried downgrading react-quill to `1.3.5` from `2.0.0-beta.2` however, the bug persisted on these two versions.
- I also tried using blots and custom formats in addition to trying this guide [https://quilljs.com/guides/cloning-medium-with-parchment/](https://quilljs.com/guides/cloning-medium-with-parchment/)
- I also tried switching to quilljs to see if the bug was because of react-quill but this didn't solve it.

## Update v2
I tested [https://quilljs.com/](https://quilljs.com/) and [https://quilljs.com/playground/](https://quilljs.com/playground/) to see if the bug was related to how Chrome rendered text and styled elements, however the examples worked just fine. I then created a new test project via create-react-app and used quill `1.3.7` and react `17.0.2`. I followed this guide [https://youtu.be/iRaelG7v0OU](https://youtu.be/iRaelG7v0OU) by Web Dev Simplified to get a basic functioning quill editor in React.

```javascript
import { useCallback } from "react";
import Quill from "quill";
import "quill/dist/quill.snow.css"

const App = () => {
  const wrapperRef = useCallback(wrapper => {
    if (wrapper == null) {
      return;
    }

    wrapper.innerHTML = "";
    const editor = document.createElement("div");
    wrapper.append(editor);
    new Quill(editor, {
      theme: "snow"
    });

  }, []);

  return (
    <div id="container" ref={wrapperRef}></div>
  );
}

export default App
```

This turned out to work just fine so this meant that it had to do with something specific to my app and not with quill/react-quill or Chrome.

I decided to check the css styling of the components inside of the react-quill editor and I came across this in the Chrome Developer Tools:
![No-Pad CSS Formatting Bug](https://user-images.githubusercontent.com/52579214/125999935-858fec8a-599a-4d64-a13c-becd4699ab8a.png)

After more debugging it seems that the CSS Reset that I added was causing this problem and adding this temporary code after the CSS Reset fixed the bug:

```css
html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed,
figure, figcaption, footer, header, hgroup,
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
  margin: 0;
  padding: 0;
  border: 0;
  font-size: 100%;
  font: inherit;
  vertical-align: baseline;
}

strong {
  font-weight: bold;
}

em {
  font-style: italic;
}
```

Testing done on:
`development` -> `experimental/downgrade-react-quill`
`development` -> `experimental/downgrade-react-quill` -> `bugfix/react-quill-inline-formatting`
`development` -> `experimental/downgrade-react-quill` -> `experimental/switching-to-quilljs`
